### ISSUE TITLE
Precise post publish tests are failing - phantomjs not in PATH

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#100]
The others are all now passing during build_and_run in docker/aws, yay! But precise is now failing with: 

```
  1) Test Flapjack before data is added Check Summary Page
     Failure/Error: visit '/'
     Cliver::Dependency::NotFound:
       Could not find an executable ["phantomjs"] on your path.
     # /var/lib/gems/1.9.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:144:in `raise_not_found!'
     # /var/lib/gems/1.9.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:116:in `detect!'
     # /var/lib/gems/1.9.1/gems/cliver-0.3.2/lib/cliver.rb:24:in `detect!'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client.rb:36:in `initialize'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client.rb:14:in `new'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/client.rb:14:in `start'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:42:in `client'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:25:in `browser'
     # /var/lib/gems/1.9.1/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
     # /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /var/lib/gems/1.9.1/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/capybara/01_no_data_spec.rb:10:in `block (2 levels) in <top (required)>'
...
Finished in 13.94 seconds (files took 0.43925 seconds to load)
18 examples, 17 failures, 1 pending
```

All the failures mention the same error about phantomjs not being in PATH. 

Full log is linked from IRC announcement: 
23:18 <roberta_> Failed build of Flapjack v1.6.0rc2 for ubuntu precise package (experimental) in 30m 4s, log: http://is.gd/boDuBZ

**Comment by jessereynolds** [comment]
Attempting to replicate locally (Mac OS) I get a different error:

```bash
FLAPJACK_COMPONENT=experimental \
  PACKAGE_FILE=flapjack_1.6.0~rc2~20150515131819~v1.6.0rc2~precise-1_amd64.deb \
  be rake post_publish_test
```
does a whole lot of stuff and eventually ends with:
```
Setting up g++ (4:4.6.3-1ubuntu5) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode.
Setting up build-essential (11.5ubuntu2.1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: puppet requires facter (< 3, > 1.6), hiera (~> 1.0), json_pure (>= 0)
STDERR:

Error running docker command, exit status is 1, duration was 6m 35s.
```

**Comment by Hobbsee** [comment]
I'm getting a different error again:

```
root@1da5c09f2c05:/# gem install puppet -v 3.7.5
ERROR:  Could not find a valid gem 'puppet' (= 3.7.5) in any repository
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SocketError: getaddrinfo: Temporary failure in name resolution (http://rubygems.org/latest_specs.4.8.gz)
```

**Comment by Hobbsee** [comment]
That was a VPN problem.

Ran this locally, the output was as follows:

```
root@15fe50f02c03:/# FACTER_flapjack_component='experimental' FACTER_flapjack_major_version='v1' FACTER_test_mode='true' FACTER_tutorial_mode='false' FACTER_with_sensu='false' puppet apply --modulepath /mnt/vagrant-flapjack/dist/modules:/etc/puppet/modules /mnt/vagrant-flapjack/dist/manifests/site.pp && cd /mnt/omnibus-flapjack
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for 15fe50f02c03 in environment production in 1.41 seconds
Notice: /Stage[main]/Flapjack::Apt/Apt::Source[flapjack]/Apt::Key[Add key: 803709B6 from Apt::Source flapjack]/Apt_key[Add key: 803709B6 from Apt::Source flapjack]/ensure: created
Notice: /Stage[main]/Phantomjs/File[/usr/local/bin/phantomjs]/ensure: created
Notice: /Stage[main]/Flapjack::Apt/Apt::Source[flapjack]/File[flapjack.list]/ensure: created
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Apt/File[/etc/apt/apt.conf.d/15update-stamp]/ensure: defined content as '{md5}92afc1e969a04f0764e9ae8343aa9f2f'
Notice: /Stage[main]/Nagios::Common/Package[nagios3]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Nagios::Common/File[/etc/nagios3/nagios.cfg]/content: content changed '{md5}90802bc75823144f0170b8ac3363ee3e' to '{md5}e4a30097db777cd12c5c91754d8d6f17'
Notice: /Stage[main]/Icinga::Common/Package[icinga]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Icinga::Common/File[/etc/icinga/icinga.cfg]/content: content changed '{md5}7b5c247e6a12d0c55ef4082903e3d829' to '{md5}083f23e9c944af289f6341dd897d222e'
Notice: /Stage[main]/Nagios::Common/File[/etc/nagios3/htpasswd.users]/ensure: defined content as '{md5}69e63b9ef70bb4ac114f6463405c927c'
Notice: /Stage[main]/Phantomjs/Exec[get phantomjs]/returns: executed successfully
Notice: /Stage[main]/Flapjack::Install/Package[flapjack]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Mailcatcher/Exec[enable-mailcatcher-in-flapjack]/returns: executed successfully
Notice: /Stage[main]/Mailcatcher/Package[libsqlite3-dev]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Mailcatcher/Exec[if [[ -f /opt/rh/ruby193/enable ]]; then echo "export PATH=\${PATH}:/opt/rh/ruby193/root/usr/local/bin" | tee -a /opt/rh/ruby193/enable && source /opt/rh/ruby193/enable; fi && gem install mailcatcher]/returns: executed successfully
Notice: /Stage[main]/Mailcatcher/Exec[mailcatcher]/returns: executed successfully
Notice: /Stage[main]/Icinga::Common/File[/etc/icinga/htpasswd.users]/ensure: defined content as '{md5}1ea264d35ecbf9a56578b16549200e23'
Notice: /Stage[main]/Icinga::Common/Service[icinga]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Flapjack::Install/Service[flapjack]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Nagios::Common/Service[nagios3]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 444.57 seconds
root@15fe50f02c03:/mnt/omnibus-flapjack# which phantomjs
/usr/local/bin/phantomjs
```

Looks like puppet missed installing some things, but didn't error out.  I'm hoping this is a heisenbug.

**Comment by jessereynolds** [comment]
Alas not, just reran all builds and just precise is failing still

16:04 <roberta> Failed build of Flapjack v1.6.0rc2 for ubuntu precise package (experimental) in 28m 43s, log: http://is.gd/LozR8M

I haven't yet checked the log
