### ISSUE TITLE
cacerts error (with 'v2_package_wip' branch)

### ISSUE THREAD

**Issue by ali-graham** [flapjack/omnibus-flapjack#104]
```
                [Software: cacerts] I | Building because `preparation' dirtied the cache
              [NetFetcher: cacerts] I | Cleaning project directory `/var/cache/omnibus/src/cacerts-2015.09.02'
              [NetFetcher: cacerts] I | `/var/cache/omnibus/cache/cacert.pem' is not an archive - copying to `/var/cache/omnibus/src/cacerts-2015.09.02'
                 [Builder: cacerts] I | Starting build
                 [Builder: cacerts] I | mkdir `/opt/flapjack/embedded/ssl/certs': 0.0004s
                 [Builder: cacerts] I | <Dynamic Ruby block>: 0.0011s
                 [Builder: cacerts] I | Build cacerts: 0.0019s
/var/lib/gems/1.9.1/bundler/gems/omnibus-software-fa5f62f05204/config/software/cacerts.rb:63:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-software-fa5f62f05204/config/software/cacerts.rb:63:in `foreach'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-software-fa5f62f05204/config/software/cacerts.rb:63:in `each'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-software-fa5f62f05204/config/software/cacerts.rb:63:in `grep'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-software-fa5f62f05204/config/software/cacerts.rb:63:in `block (2 levels) in evaluate'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:870:in `instance_eval'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:870:in `run'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:701:in `block (3 levels) in execute'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:723:in `call'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:723:in `with_retries'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:700:in `block (2 levels) in execute'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/instrumentation.rb:23:in `call'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/instrumentation.rb:23:in `measure'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:699:in `block in execute'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:773:in `call'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:773:in `with_clean_env'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:698:in `execute'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:594:in `block (2 levels) in build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:593:in `each'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:593:in `block in build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/instrumentation.rb:23:in `call'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/instrumentation.rb:23:in `measure'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/builder.rb:592:in `build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/software.rb:892:in `execute_build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/software.rb:767:in `build_me'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/project.rb:1006:in `block in build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/project.rb:1005:in `each'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/project.rb:1005:in `build'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/cli.rb:83:in `build'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/cli/base.rb:33:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/lib/omnibus/cli.rb:41:in `execute!'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-0e658a8da494/bin/omnibus:11:in `<top (required)>'
	from bin/omnibus:16:in `load'
	from bin/omnibus:16:in `<main>'
```

Mac OS X 10.11, VirtualBox 5.0.4

```
Boot2Docker version 1.8.1, build master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
Docker version 1.8.1, build d12ea79
```

```
export BUILD_REF="d8c7e0b94197c7e12f934f8af32292a7ae3316cd"
export DISTRO="ubuntu"
export DISTRO_RELEASE="precise"
bundle exec rake build
```

**Comment by ali-graham** [comment]
On @jessereynolds advice, used docker to get a shell in the container image, and it hadn't checked out the branch for `omnibus-flapjack`, was still on `master`; after checking out the new branch in the `/omnibus-flapjack` directory and re-running the build using `bundle exec bin/omnibus build flapjack`, it errored with the same message as above.

**Comment by jessereynolds** [comment]
I think @SarahKowalik's changes to omnibus have been merged into master now so perhaps try changing the location of the omnibus gem in Gemfile to chef/omnibus to get the latest version. I wonder if we have a problem due to using the latest omnibus-software (which is written for omnibus 4.1.x) but we're using omnibus 4.0.0? Could be a bit of a long shot.
