### ISSUE TITLE
flapjack gem now requires a mysql client and headers

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#73]
We now need to build a mysql client and headers with omnibus in order to satisfy the dependencies of the mysql2 gem recently added to flapjack, along the lines of http://packages.ubuntu.com/precise/libmysqlclient-dev

This is blocking all package builds 

```
                [Builder: flapjack] I | Build flapjack: 175.6838s
                [Builder: flapjack] I | Finished build
               [Software: flapjack] I | Dirtied the cache
                      [HealthCheck] E | Failed!
                      [HealthCheck] E | The following libraries have unsafe or unmet dependencies:
    --> /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2/mysql2.so
    --> /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/ext/mysql2/mysql2.so

                      [HealthCheck] E | The following binaries have unsafe or unmet dependencies:

                      [HealthCheck] E | The following libraries cannot be guaranteed to be on target systems:
    --> /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007fbcc6143000)
    --> /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007ff3def0b000)

```

**Comment by jessereynolds** [comment]
14:18 <roberta> Failed build of Flapjack v1.2.2 for ubuntu precise package (experimental) in 11m 44s, log: http://is.gd/55hRuM

Added a mysql-client.rb software definition, but it's error'ing as follows:

```
           [Software: mysql-client] I | Building because `preparation' dirtied the cache
         [NetFetcher: mysql-client] I | Cleaning project directory `/var/cache/omnibus/src/mysql-5.5.37'
         [NetFetcher: mysql-client] I | Extracting `/var/cache/omnibus/cache/mysql-5.5.37.tar.gz' to `/var/cache/omnibus/src'
            [Builder: mysql-client] I | Starting build
            [Builder: mysql-client] I | Environment:
            [Builder: mysql-client] I |   CFLAGS="-I/opt/flapjack/embedded/include"
            [Builder: mysql-client] I |   CPPFLAGS="-L/opt/flapjack/embedded/lib -I/opt/flapjack/embedded/include"
            [Builder: mysql-client] I |   CXXFLAGS="-L/opt/flapjack/embedded/lib -I/opt/flapjack/embedded/include"
            [Builder: mysql-client] I |   LDFLAGS="-Wl,-rpath,/opt/flapjack/embedded/lib -L/opt/flapjack/embedded/lib"
            [Builder: mysql-client] I |   LD_RUN_PATH="/opt/flapjack/embedded/lib"
            [Builder: mysql-client] I |   PATH="/opt/flapjack/bin:/opt/flapjack/embedded/bin:/var/lib/gems/1.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
            [Builder: mysql-client] I |   PKG_CONFIG_PATH="/opt/flapjack/embedded/lib/pkgconfig"
            [Builder: mysql-client] I | $ cmake -DCMAKE_SKIP_RPATH=YES -DCMAKE_INSTALL_PREFIX=/opt/flapjack/embedded -DWITH_SSL=system -DOPENSSL_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DOPENSSL_LIBRARIES:FILEPATH=/opt/flapjack/embedded/lib/libssl.so -DWITH_ZLIB=system -DZLIB_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DZLIB_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libz.so -DCRYPTO_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libcrypto.so .
            [Builder: mysql-client] I | Execute: `cmake -DCMAKE_SKIP_RPATH=YES -DCMAKE_INSTALL_PREFIX=/opt/flapjack/embedded -DWITH_SSL=system -DOPENSSL_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DOPENSSL_LIBRARIES:FILEPATH=/opt/flapjack/embedded/lib/libssl.so -DWITH_ZLIB=system -DZLIB_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DZLIB_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libz.so -DCRYPTO_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libcrypto.so .': 0.022s
            [Builder: mysql-client] I | Build mysql-client: 0.023s
/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:294:in `exec': No such file or directory - cmake -DCMAKE_SKIP_RPATH=YES -DCMAKE_INSTALL_PREFIX=/opt/flapjack/embedded -DWITH_SSL=system -DOPENSSL_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DOPENSSL_LIBRARIES:FILEPATH=/opt/flapjack/embedded/lib/libssl.so -DWITH_ZLIB=system -DZLIB_INCLUDE_DIR:PATH=/opt/flapjack/embedded/include -DZLIB_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libz.so -DCRYPTO_LIBRARY:FILEPATH=/opt/flapjack/embedded/lib/libcrypto.so . (Errno::ENOENT)
	from /var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:294:in `block in fork_subprocess'
	from /var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:276:in `fork'
	from /var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:276:in `fork_subprocess'
	from /var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:52:in `run_command'
	from /var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:242:in `run_command'
	from /var/lib/gems/1.9.1/bundler/gems/omnibus-c24f9bef379b/lib/omnibus/util.rb:81:in `shellout'
```

**Comment by jessereynolds** [comment]
current status:
- added [mysql-client.rb](https://github.com/flapjack/omnibus-flapjack/blob/5b23ed89a9cfba6efb22afc628a852c5a985a1bb/config/software/mysql-client.rb) omnibus software definition 
- trusty builds the package fine with this on my mac using the docker built, but fails to start the docker container on ec2 with:
```
Status: Downloaded newer image for flapjack/omnibus-ubuntu:trusty
time="2015-02-12T09:34:00Z" level="fatal" msg="Error response from daemon: Cannot start container d357780f25fb67574f4ea0f94ccd127a2d291b93c6fa4887a5c715788d50f0e2: Error getting container d357780f25fb67574f4ea0f94ccd127a2d291b93c6fa4887a5c715788d50f0e2 from driver devicemapper: Error mounting '/dev/mapper/docker-202:1-32071-d357780f25fb67574f4ea0f94ccd127a2d291b93c6fa4887a5c715788d50f0e2' on '/var/lib/docker/devicemapper/mnt/d357780f25fb67574f4ea0f94ccd127a2d291b93c6fa4887a5c715788d50f0e2': no such file or directory" 
```
- precise fails locally and on ec2 as libssl.so is not found in the expected location `/opt/flapjack/embedded/lib/libssl.so`
```
/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout/unix.rb:294:in `exec': No such file or directory - file /opt/flapjack/embedded/lib/libssl.so (Errno::ENOENT)
```
- debian and centos are also both broken but i'm not taking too much notice of why just yet

**Comment by jessereynolds** [comment]
Trusty package has completed on ec2 on a second attempt. However subsequent testing is failing: 

 <roberta> Failed build of Flapjack v1.2.2 for ubuntu trusty package (experimental) in 34m 33s, log: http://is.gd/9APoIc

```
Failures:

  1) Process "flapjack" should be running
     Failure/Error: it { should be_running }
       expected Process "flapjack" to be running
       /bin/sh -c ps\ -C\ flapjack\ -o\ pid\=\ \|\ head\ -1
       
     # ./spec/serverspec/flapjack_spec.rb:33:in `block (2 levels) in <top (required)>'

...snip...

Finished in 2.82 seconds (files took 0.5673 seconds to load)
48 examples, 12 failures

Failed examples:

rspec ./spec/serverspec/flapjack_spec.rb:33 # Process "flapjack" should be running
rspec ./spec/serverspec/flapjack_spec.rb:34 # Process "flapjack" args should match /\/opt\/flapjack\/bin\/flapjack server start/
rspec ./spec/serverspec/flapjack_spec.rb:38 # Port "3080" should be listening
rspec ./spec/serverspec/flapjack_spec.rb:42 # Port "3081" should be listening
rspec ./spec/serverspec/flapjack_spec.rb:80 # File "/var/log/flapjack/jsonapi_access.log" should be file
rspec ./spec/serverspec/flapjack_spec.rb:81 # File "/var/log/flapjack/jsonapi_access.log" should be mode 644
rspec ./spec/serverspec/flapjack_spec.rb:82 # File "/var/log/flapjack/jsonapi_access.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:83 # File "/var/log/flapjack/jsonapi_access.log" should be grouped into "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:94 # File "/var/log/flapjack/web_access.log" should be file
rspec ./spec/serverspec/flapjack_spec.rb:95 # File "/var/log/flapjack/web_access.log" should be mode 644
rspec ./spec/serverspec/flapjack_spec.rb:96 # File "/var/log/flapjack/web_access.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:97 # File "/var/log/flapjack/web_access.log" should be grouped into "flapjack"

STDERR: 
Unable to find image 'ubuntu:trusty' locally
ubuntu:trusty: The image you are pulling has been verified
511136ea3c5a: Already exists
27d47432a69b: Already exists
5f92234dcf1e: Already exists
51a9c7c1f8bb: Already exists
5ba9dab47459: Already exists
Status: Image is up to date for ubuntu:trusty
ERROR running docker command, exit status is 1, duration was 12m 22s.
```

**Comment by jessereynolds** [comment]
And this looks to be the cause of the failing package installation:

```
Preparing to unpack .../flapjack_1.2.2~+20150213005839~v1.2.2~trusty-1_amd64.deb ...
Unpacking flapjack (1.2.2~+20150213005839~v1.2.2~trusty-1) ...
Setting up flapjack (1.2.2~+20150213005839~v1.2.2~trusty-1) ...
Creating /etc/flapjack/flapjack_config.yaml
Creating /usr/local/lib/flapjackfeeder.o
Creating /etc/init.d/redis-flapjack
Creating /etc/init.d/flapjack
Creating /etc/init.d/flapjack-nagios-receiver
Creating /etc/init.d/flapper
Setting paths
Starting redis-flapjack
Starting redis-server: redis-server.
Starting flapjack
Flapjack starting...flapjack[71]: 2015-02-13T01:20:57+00:00 [FATAL] :: flapjack-coordinator :: Mysql2::Error
Unknown MySQL server host 'x.x.x.x' (0)
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.2.2/lib/flapjack/gateways/sms_gammu.rb:47:in `new'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.2.2/lib/flapjack/gateways/sms_gammu.rb:47:in `start'
/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-1.2.2/lib/flapjack/pikelet.rb:126:in `block in start'

flapjack[71]: 2015-02-13T01:20:57+00:00 [ERROR] :: flapjack-processor :: Invalid event data received, Event hash has missing keys 'state', 'entity', 'check' {"type"=>"noop"}

Daemon has started successfully
 done.
Thank you for installing flapjack!

Log in again to have /opt/flapjack/bin added to your PATH or run:
  export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/flapjack/bin

Flapjack should now be running. Visit http://localhost:3080/
```

**Comment by jessereynolds** [comment]
The default config has sms_gammu enabled on startup, which is causing flapjack to explode on startup as the default config for the gateway is invalid.

**Comment by jessereynolds** [comment]
Gammu gateway has been removed for now, see https://github.com/flapjack/flapjack/pull/759#issuecomment-74201504
