### ISSUE TITLE
1.3.0rc2 debian package test failures - /bin/sh: 1: ps: not found

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#76]
21:10 <roberta> Failed build of Flapjack v1.3.0rc2 for debian wheezy package (experimental) in 21m 7s, log: http://is.gd/wzi9wk

```
Failures:

  1) Process "redis-server" args should match /0.0.0.0:6380/
     Failure/Error: its(:args) { should match /0.0.0.0:6380/ }
       expected "/bin/sh: 1: ps: not found" to match /0.0.0.0:6380/
       Diff:
       @@ -1,2 +1,2 @@
       -/0.0.0.0:6380/
       +"/bin/sh: 1: ps: not found"
       /bin/sh -c ps\ -C\ redis-server\ -o\ args\=\ \|\ head\ -1
       /bin/sh: 1: ps: not found

     # ./spec/serverspec/flapjack_spec.rb:29:in `block (2 levels) in <top (required)>'

  2) Process "flapjack" args should match /\/opt\/flapjack\/bin\/flapjack server start/
     Failure/Error: its(:args) { should match   /\/opt\/flapjack\/bin\/flapjack server start/ }
       expected "/bin/sh: 1: ps: not found" to match /\/opt\/flapjack\/bin\/flapjack server start/
       Diff:
       @@ -1,2 +1,2 @@
       -/\/opt\/flapjack\/bin\/flapjack server start/
       +"/bin/sh: 1: ps: not found"
       /bin/sh -c ps\ -C\ flapjack\ -o\ args\=\ \|\ head\ -1
       /bin/sh: 1: ps: not found

     # ./spec/serverspec/flapjack_spec.rb:34:in `block (2 levels) in <top (required)>'

Finished in 2.42 seconds (files took 0.51808 seconds to load)
28 examples, 2 failures

Failed examples:

rspec ./spec/serverspec/flapjack_spec.rb:29 # Process "redis-server" args should match /0.0.0.0:6380/
rspec ./spec/serverspec/flapjack_spec.rb:34 # Process "flapjack" args should match /\/opt\/flapjack\/bin\/flapjack server start/
```

**Comment by Hobbsee** [comment]
```
omnibus-flapjack ➤ docker run -i -t --rm debian:wheezy bash
root@033c78ed2fa2:/# ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  selinux	srv  sys  tmp  usr  var
root@033c78ed2fa2:/# ps
bash: ps: command not found
root@033c78ed2fa2:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@033c78ed2fa2:/# ls -lh /bin/ps
ls: cannot access /bin/ps: No such file or directory
```

Wow.

**Comment by Hobbsee** [comment]
https://stackoverflow.com/questions/26982274/ps-command-doesnt-work-in-docker-container
