### ISSUE TITLE
centos publish fails with package filename mismatch

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#89]
The package filename expected by the rake publish task does not match the filename of the generated package: 

```
flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm   <- expected package filename
flapjack-1.4.0_0.20150312130042rc1.el6-1.el6.x86_64.rpm   <- actual package filename
```

```
                      [HealthCheck] I | Running health on flapjack
                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), tildes (~) and underscores (_). Converting `1.4.0_0.20150312130042rc1.el6' to `1.4.0_0.20150312130042rc1.el6'.
                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), tildes (~) and underscores (_). Converting `1.4.0_0.20150312130042rc1.el6' to `1.4.0_0.20150312130042rc1.el6'.
                    [Packager::RPM] I | Rendering `/opt/rh/ruby193/root/usr/local/share/gems/bundler/gems/omnibus-ef1d05d45da5/resources/rpm/spec.erb' to `/tmp/flapjack20150312-203-e3bosn/SPECS/flapjack-1.4.0_0.20150312130042rc1.el6-1.el6.x86_64.rpm.spec'
                    [Packager::RPM] I | Signing enabled for .rpm file
                    [Packager::RPM] I | Detected .rpmmacros file at `/root'
                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), tildes (~) and underscores (_). Converting `1.4.0_0.20150312130042rc1.el6' to `1.4.0_0.20150312130042rc1.el6'.
                    [Packager::RPM] I | Rendering `/opt/rh/ruby193/root/usr/local/share/gems/bundler/gems/omnibus-ef1d05d45da5/resources/rpm/signing.erb' to `/tmp/d20150312-203-1cj5z2e/sign-rpm'
                    [Packager::RPM] I | Creating .rpm file
                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), tildes (~) and underscores (_). Converting `1.4.0_0.20150312130042rc1.el6' to `1.4.0_0.20150312130042rc1.el6'.
                    [Packager::RPM] W | The `version' component of RPM package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots (.), plus signs (+), tildes (~) and underscores (_). Converting `1.4.0_0.20150312130042rc1.el6' to `1.4.0_0.20150312130042rc1.el6'.
                       [Compressor] I | No compressor defined for `rhel'.
warning: flapjack-1.4.0_0.20150312130042rc1.el6-1.el6.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 803709b6: NOKEY
STDERR:

Docker run completed, duration was 14m 38s.
Retrieving package from the container
Purging the container
Uploading flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm packages to http://packages.flapjack.io/tmp/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm
rake aborted!
Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of aws s3 cp pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm s3://packages.flapjack.io/tmp/ --acl public-read --region us-east-1 2>&1 ----
STDOUT: [Errno 2] No such file or directory: '/home/ubuntu/omnibus-flapjack/pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm'
Completed 1 part(s) with ... file(s) remaining
STDERR:
---- End output of aws s3 cp pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm s3://packages.flapjack.io/tmp/ --acl public-read --region us-east-1 2>&1 ----
Ran aws s3 cp pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm s3://packages.flapjack.io/tmp/ --acl public-read --region us-east-1 2>&1 returned 1
/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
/home/ubuntu/omnibus-flapjack/Rakefile:109:in `block in <top (required)>'
Tasks: TOP => build_and_publish => build
(See full trace by running task with --trace)
[Errno 2] No such file or directory: '/home/ubuntu/omnibus-flapjack/pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm'
Completed 1 part(s) with ... file(s) remaining

I, [2015-03-12T13:15:36.306123 #1787]  INFO -- : Failed build of v1.4.0rc1 on centos 6 at 2015-03-12T13:15:36Z, duration: 14m 55s

^C
ubuntu@ip-10-63-53-207:~/omnibus-flapjack$ ls -l /home/ubuntu/omnibus-flapjack/pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm
ls: cannot access /home/ubuntu/omnibus-flapjack/pkg/flapjack-1.4.0_0.20150312130042rc1.el6-1.x86_64.rpm: No such file or directory
ubuntu@ip-10-63-53-207:~/omnibus-flapjack$ set -o vi
ubuntu@ip-10-63-53-207:~/omnibus-flapjack$ ls -l /home/ubuntu/omnibus-flapjack/pkg/
total 75180
-rw-r--r-- 1 ubuntu ubuntu 76976235 Mar 12 13:15 flapjack-1.4.0_0.20150312130042rc1.el6-1.el6.x86_64.rpm
-rw-r--r-- 1 ubuntu ubuntu      618 Mar 12 13:15 flapjack-1.4.0_0.20150312130042rc1.el6-1.el6.x86_64.rpm.metadata.json
```

**Comment by jessereynolds** [comment]
23:45 <roberta> Failed build of Flapjack v1.4.0rc1 for centos 6 package (experimental) in 14m 55s, log: http://is.gd/Tj4wE1
