### ISSUE TITLE
unable to publish ubuntu precise package

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#91]
Packages built and published successfully for centos 6, debian wheezy, and ubuntu trusty, but ubuntu precise is failing:

15:34 <roberta> Failed build of Flapjack v1.4.0rc1 for ubuntu precise package (experimental) in 17m 41s, log: http://is.gd/Cp2bOZ

It seems to end up wanting a local copy of an older package, 1.3.0rc2, for some reason:

```
ERROR: unable to publish: unable to process packages: stat /home/ubuntu/omnibus-flapjack/aptly/pool/19/e0/flapjack_1.3.0~rc2~20150216045853~v1.3.0rc2~precise-1_amd64.deb: no such file or directory
```

tail end of the build and publish log:

```
Adding pkg/flapjack_1.4.0~rc1~20150313044646~v1.4.0rc1~precise-1_amd64.deb to the flapjack-v1-precise-experimental repo
Loading packages...
[+] flapjack_1.4.0~rc1~20150313044646~v1.4.0rc1~precise-1_amd64 added
Attempting the first publish for all components of the major version of the given distro release
ERROR: prefix/distribution already used by another published repo: v1/precise [amd64, i386] publishes {experimental: [flapjack-v1-precise-experimental]}, {main: [flapjack-v1-precise-main]}
Repository already published, attempting an update
rake aborted!
Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update precise v1 2>&1 ----
STDOUT: WARNING: force overwrite mode enabled, aptly might corrupt other published repositories sharing the same package pool.

Loading packages...
Generating metadata files and linking package files...
ERROR: unable to publish: unable to process packages: stat /home/ubuntu/omnibus-flapjack/aptly/pool/19/e0/flapjack_1.3.0~rc2~20150216045853~v1.3.0rc2~precise-1_amd64.deb: no such file or directory
STDERR: 
---- End output of aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update precise v1 2>&1 ----
Ran aptly -config=aptly.conf -gpg-key="803709B6" -force-overwrite=true publish update precise v1 2>&1 returned 1/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
/var/lib/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
/home/ubuntu/omnibus-flapjack/lib/omnibus-flapjack/publish.rb:131:in `add_to_deb_repo'
/home/ubuntu/omnibus-flapjack/Rakefile:308:in `block (2 levels) in <top (required)>'
/home/ubuntu/omnibus-flapjack/Rakefile:303:in `block in <top (required)>'
Tasks: TOP => build_and_publish => publish
(See full trace by running task with --trace)
WARNING: force overwrite mode enabled, aptly might corrupt other published repositories sharing the same package pool.

Loading packages...
Generating metadata files and linking package files...
ERROR: unable to publish: unable to process packages: stat /home/ubuntu/omnibus-flapjack/aptly/pool/19/e0/flapjack_1.3.0~rc2~20150216045853~v1.3.0rc2~precise-1_amd64.deb: no such file or directory

I, [2015-03-13T05:04:27.205537 #922]  INFO -- : Failed build of v1.4.0rc1 on ubuntu precise at 2015-03-13T05:04:27Z, duration: 17m 41s

```

**Comment by Hobbsee** [comment]
I think aptly lost its marbles here - the package did exist in a number of places, but not where it expected to find it.

I unpublished, removed the package from the repo, republished, and all is now fine.
