### ISSUE TITLE
failing to build go-lang components in flapjack master

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#95]
Eg:

18:52 <roberta> Failed build of Flapjack master for ubuntu trusty package (experimental) in 12m 38s, log: http://is.gd/26A5xV

Log exercept:

```
    $ LC_ALL=C export gem_home=/`/opt/flapjack/embedded/bin/gem list --all --details flapjack |   grep 'Installed at' | sed 's/^.* \///'` ; echo "gem_home: ${gem_home}" ; export installed_gem=`ls -dtr ${gem_home}/gems/flapjack* | tail -1` ; cd ${installed_gem} && ./build.sh

Output:

    gem_home: /opt/flapjack/embedded/lib/ruby/gems/2.1.0
--- FAIL: TestSendSucceeds (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x445ac7]

goroutine 23 [running]:
runtime.panic(0x5c4820, 0x6fc5d3)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
testing.func·006()
	/usr/local/go/src/pkg/testing/testing.go:416 +0x176
runtime.panic(0x5c4820, 0x6fc5d3)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
flapjack.Transport.Send(0x0, 0x0, 0x0, 0x0, 0x0, 0x5ed4d0, 0x5, 0x5f0450, 0x5, 0x0, ...)
	/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/src/flapjack/transport.go:39 +0x237
flapjack.TestSendSucceeds(0xc208050000)
	/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/src/flapjack/transport_test.go:24 +0xaf
testing.tRunner(0xc208050000, 0x6fafa8)
	/usr/local/go/src/pkg/testing/testing.go:422 +0x8b
created by testing.RunTests
	/usr/local/go/src/pkg/testing/testing.go:504 +0x8db

goroutine 16 [chan receive]:
testing.RunTests(0x646288, 0x6faf60, 0x5, 0x5, 0x1)
	/usr/local/go/src/pkg/testing/testing.go:505 +0x923
testing.Main(0x646288, 0x6faf60, 0x5, 0x5, 0x704a40, 0x0, 0x0, 0x704a40, 0x0, 0x0)
	/usr/local/go/src/pkg/testing/testing.go:435 +0x84
main.main()
	flapjack/_test/_testmain.go:55 +0x9c

goroutine 19 [finalizer wait]:
runtime.park(0x413440, 0x7005c8, 0x6ff109)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x7005c8, 0x6ff109)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445
FAIL	flapjack	0.007s

```

**Comment by jessereynolds** [comment]
Related to this PR merge today: https://github.com/flapjack/flapjack/commit/4b0bfa8f3567c69e73b2d9af0921565dc56c0c0f#diff-5e6bfa99eef2554244c1744d9934540bR24

**Comment by jessereynolds** [comment]
@rebyn - any ideas what's happening here?

**Comment by rebyn** [comment]
I have no idea. Any Go guru passing by that can take a look? @auxesis

**Comment by auxesis** [comment]
Fixed, and per the request outside this issue, pushed to master in flapjack/flapjack@483f0849c9add2dcd0f3d22a035d5d1fe7a02100.
